//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InforSignature.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\maiks\\Desktop\\Assinar\\Filial1;C:\\Users\\maiks\\Desktop\\Assinar\\Filial1\\Con" +
            "fig\\Infordoc 2020.pfx;Infordoc01;C:\\Users\\maiks\\Desktop\\Assinar\\Filial1\\Config\\W" +
            "atermark.jpg;superior-direita")]
        public string Filial1 {
            get {
                return ((string)(this["Filial1"]));
            }
            set {
                this["Filial1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\maiks\\Desktop\\Assinar\\Filial2;C:\\Users\\maiks\\Desktop\\Assinar\\Filial2\\Con" +
            "fig\\Infordoc 2020.pfx;Infordoc01;C:\\Users\\maiks\\Desktop\\Assinar\\Filial1\\Config\\W" +
            "atermark.jpg;superior-direita")]
        public string Filial2 {
            get {
                return ((string)(this["Filial2"]));
            }
            set {
                this["Filial2"] = value;
            }
        }
    }
}
